### ISSUE TITLE
change text in quick-start.md for authentication using token

### ISSUE THREAD

**Issue by hbuter-rubrik** [rubrikinc/rubrik-sdk-for-python#263]
currently in the quick-start.md the following is written under the authentication section:

Or by passing the node IP and API Token as follows:

```
node_ip = "192.168.0.100"
api_token = "jf2jma02k3anms0"

rubrik = rubrik_cdm.Connect(node_ip, api_token)
```

this is not working and it should be changed into: 

Or by passing the node IP and API Token as follows:

```
node_ip = "192.168.0.100"
api_token = "jf2jma02k3anms0"

rubrik = rubrik_cdm.Connect(node_ip, api_token=api_token)
```

**Comment by jaapbrasser** [comment]
Hello @hbuter-rubrik,

Thanks for reporting this I'll make sure this gets updated asap!

**Comment by marcolussetti** [comment]
Hi @jaapbrasser -- when one clicks on "Quick Start" on https://build.rubrik.com/sdks/python/, they are pointed to https://github.com/rubrikinc/rubrik-sdk-for-python/blob/master/docs/quick-start.md which still has the issue because it's on the master branch. Is there any chance these changes could be merged back into master to make it clear for people?

**Comment by marcolussetti** [comment]
Actually, I think Jaap has moved on to other projects, so perhaps I should tag @mwpreston instead.
