### ISSUE TITLE
Add support for IPv6 connections

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#39]
**Is your feature request related to a problem? Please describe.**

Unable to bootstrap a cluster based off of its IPv6 address

**Describe the solution you'd like**

Add support for IPv6 management addresses in the SDK.

**Additional context**

Something similar to this should work. We need to allow for `[]` for the IP address which is how you populate IPv6 addresses in `requests`.

```python
if call_type == 'GET':

    request_url = "https://{}/api/{}{}".format(

    self.node_ip, api_version, api_endpoint)

    request_url = quote(request_url, '://?=&').replace('%5B', '[').replace('%5D', ']')

    self.log('GET {}'.format(request_url))
```

**Comment by drew-russell** [comment]
@shamsway switching this to a doc enhancement.

Customer confirmed that they used mdns (i.e `VRVW2313982B4.local`) as the address. Can you just update the docs with this info and maybe an example?

**Comment by shamsway** [comment]
@drew-russell I've been poking at this for a good part of the day, and I have a good bit of information I can add to the docs regarding IPv6 mDNS resolution and related info. Unfortunately I've hit a wall trying to replicate bootstrapping using the mDNS address on linux+python3. I'll try Windows as well, perhaps it's handled differently at the OS level.

With linux and python3, there are some issues connecting to link-local IPv6 addresses. By default I get an error along the lines of `<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd1632127f0>: Failed to establish a new connection: [Errno 113] No route to host` when trying to connect via mDNS (i.e. `print(requests.get('VRVW4217DB4E3.local').text)`). This makes sense because the OS is expecting an interface name to be supplied at the end of the IPv6 address for a link-local address (e.g. `fdd4:c664:1f69:bb0d:250:56ff:fe97:31cf%ens160`), and the normal name resolution process doesn't provide enough info to do that. Down at the socket level, this is easy to resolve by using `socket.getaddrinfo()` since it will return all the necessary information for a link-local connection. Unfortunately it requires some patching to surface that up to the urllib3/requests level, and it would likely be somewhat ugly. I'm going to continue testing and see if I can come up with a workaround. It may be worth the effort to follow up with the customer to get some more information from them on how they solved this. Either way, accomplishing this on linux will likely require new code in addition to new documentation. 

Additional info: 
* https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6/50044152#50044152
https://stackoverflow.com/questions/4030269/why-doesnt-a-en0-suffix-work-to-connect-a-link-local-ipv6-tcp-socket-in-python
