### ISSUE TITLE
On Demand Snapshot for NAS Shares

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#50]
**Describe the solution you'd like**

Add NAS Share support to the `on_demand_snapshot()` function

**Additional context**

Customer request.

**Comment by awhite1159** [comment]
Hi Drew. I am actually the one that made the request. But, I also wrote a method to accomplish using the API. I know there are certain requirements that need to be met in order to add it to the SDK. I'm kind of green with Github. Where could I find the requirements to be met in order to have my method added to the SDK or at least considered?

**Comment by drew-russell** [comment]
@awhite1159 awesome! 

We have a contributing guide that reviews the requirements: https://github.com/rubrikinc/rubrik-sdk-for-python/blob/master/CONTRIBUTING.md

Happy to help walk you through anything that may be confusing, or we don't have enough detail listed.

**Comment by awhite1159** [comment]
Thanks Drew. I'm looking at the link you sent.
